# Site settings
title: Grayscale
email: info@ygol.com
url: https://ygol.github.io
description: "I'm Yves Goldberg.I do not blog frequently at http://www.120467.com I work at http://www.ygol.com Ygol InterNetworking where I passionately help companies deploy their ERP system using the Open Source www.odoo.com Odoo"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Yves Goldberg

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/ygol

  - title: Quora
    url: https://www.quora.com/profile/Yves-Goldberg
#  - title: facebook
#    url:
#  - title: stack-overflow
#    url: http://stackoverflow.com/questions/tagged/ygol
#  - title: bitbucket
#    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/ygol

# Build settings
markdown: kramdown
permalink: pretty
